[package]
edition = "2021"
name = "upload-endpoint"
version = "0.1.0"

[dependencies]
axum = {version = "0.8.1", features = ["multipart"]}
clap = {version = "4", features = ["derive"]}
reqwest = {version = "0.12.14", features = ["multipart"]}
tokio = {version = "1.35.0", features = ["full"]}
