[package]
name = "file-uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }
pbr = "1.0.4"